import { 
    mdiBagCarryOn,
    mdiBriefcase,
    mdiCamera,
    mdiLaptop,
    mdiEarth,
    mdiPassport,
    mdiKeyVariant,
    mdiCreditCardOutline,
    mdiCashMultiple,
    mdiShieldOutline,
    mdiMapMarker,
    mdiFaceMan,
    mdiFaceWoman,
    mdiBaby,
    mdiTshirtCrew,
    mdiToothbrush,
    mdiHanger,
    mdiTie,
    mdiLingerie,
    mdiHumanBabyChangingTable,
    mdiHumanPregnant,
    mdiBabyCarriage,
    mdiBed,
    mdiHomeVariant,
    mdiPaperRollOutline,
    mdiPill,
    mdiMedicalBag,
    mdiVirus,
    mdiRadiator,
    mdiAirConditioner,
    mdiDog,
    mdiHammerWrench,
    mdiLightbulbOnOutline,
    mdiCity, 
    mdiAirplane,
    mdiBus,
    mdiTrain,
    mdiCar,
    mdiFerry,
    mdiMoped,
    mdiRvTruck,
    mdiWeatherSunny,
    mdiWeatherCloudy,
    mdiWeatherPouring,
    mdiWeatherSnowy,
    mdiWeatherWindyVariant,
    mdiWeatherHail,
    mdiSnowflake,
    mdiThermometerHigh,
    mdiThermometerLow,
    mdiBeach,
    mdiSwim,
    mdiWalk,
    mdiBike,
    mdiHiking,
    mdiHorseshoe,
    mdiSki,
    mdiSailBoat,
    mdiTent,
    mdiSpaOutline,
    mdiShopping,
    mdiBookOpenPageVariant,
    mdiChessPawn,
    mdiCardsClub,
    mdiControllerClassic,
    mdiPalette,
    mdiMusic,
    mdiTelevision,
    mdiFountainPenTip,
    mdiChefHat,
    mdiTree,
    mdiFlower,
    mdiShovel,
    mdiCastle,
    mdiDramaMasks,
    mdiSilverware,
    mdiDrag,
} from '@mdi/js';


export default {
    'bag-carry-on': mdiBagCarryOn,
    'briefcase': mdiBriefcase,
    'camera': mdiCamera,
    'laptop': mdiLaptop,
    'earth': mdiEarth,
    'passport': mdiPassport,
    'key-variant': mdiKeyVariant,
    'credit-card-outline': mdiCreditCardOutline,
    'cash-multiple': mdiCashMultiple,
    'shield-outline': mdiShieldOutline,
    'map-marker': mdiMapMarker,
    'face': mdiFaceMan,
    'face-woman': mdiFaceWoman,
    'baby': mdiBaby,
    'tshirt-crew': mdiTshirtCrew,
    'toothbrush': mdiToothbrush,
    'hanger': mdiHanger,
    'tie': mdiTie,
    'lingerie': mdiLingerie,
    'human-baby-changing-table': mdiHumanBabyChangingTable,
    'human-pregnant': mdiHumanPregnant,
    'baby-carriage': mdiBabyCarriage,
    'bed': mdiBed,
    'home-variant': mdiHomeVariant,
    'paper-roll-outline': mdiPaperRollOutline,
    'pill': mdiPill,
    'medical-bag': mdiMedicalBag,
    'virus': mdiVirus,
    'radiator': mdiRadiator,
    'air-conditioner': mdiAirConditioner,
    'dog': mdiDog,
    'hammer-wrench': mdiHammerWrench,
    'lightbulb-on-outline': mdiLightbulbOnOutline,
    'city': mdiCity,
    'airplane': mdiAirplane,
    'bus': mdiBus,
    'train': mdiTrain,
    'car': mdiCar,
    'ferry': mdiFerry,
    'moped': mdiMoped,
    'rv-truck': mdiRvTruck,
    'weather-sunny': mdiWeatherSunny,
    'weather-cloudy': mdiWeatherCloudy,
    'weather-pouring': mdiWeatherPouring,
    'weather-snowy': mdiWeatherSnowy,
    'weather-windy-variant': mdiWeatherWindyVariant,
    'weather-hail': mdiWeatherHail,
    'snowflake': mdiSnowflake,
    'thermometer-high': mdiThermometerHigh,
    'thermometer-low': mdiThermometerLow,
    'beach': mdiBeach,
    'swim': mdiSwim,
    'walk': mdiWalk,
    'bike': mdiBike,
    'hiking': mdiHiking,
    'horseshoe': mdiHorseshoe,
    'ski': mdiSki,
    'sail-boat': mdiSailBoat,
    'tent': mdiTent,
    'spa-outline': mdiSpaOutline,
    'shopping': mdiShopping,
    'book-open-page-variant': mdiBookOpenPageVariant,
    'chess-pawn': mdiChessPawn,
    'cards-club': mdiCardsClub,
    'controller-classic': mdiControllerClassic,
    'palette': mdiPalette,
    'music': mdiMusic,
    'television': mdiTelevision,
    'fountain-pen-tip': mdiFountainPenTip,
    'chef-hat': mdiChefHat,
    'tree': mdiTree,
    'flower': mdiFlower,
    'shovel': mdiShovel,
    'castle': mdiCastle,
    'drama-masks': mdiDramaMasks,
    'silverware': mdiSilverware,
    'drag': mdiDrag,
} as { [key: string]: string }